base_url = "https://dhirajgagrai.dev"
title = "Dhiraj Gagrai"

compile_sass = false

build_search_index = true

theme = "apollo"

[markdown]
highlight_code = true

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "auto"      

menu = [
    { name = "home", url = "/", weight = 1 },
    { name = "posts", url = "/posts", weight = 2 },
    { name = "now?", url = "/now", weight = 2 },
]

stylesheets = [
    "css/base.css"
]