base_url = "https://dhirajgagrai.dev"
title = "Dhiraj Gagrai"

compile_sass = true
build_search_index = true

theme = "apollo"

[markdown]
highlight_code = true

[extra]
toc = true
use_cdn = false
favicon = "/icon/Banana_Enthusiast.png"
theme = "toggle"      

menu = [
    { name = "posts", url = "/posts", weight = 1 },
    { name = "notes", url = "/notes", weight = 2 },
    { name = "now?", url = "/now", weight = 3 },
]

stylesheets = [
    "css/base.css"
]